### ISSUE TITLE
Grails outdated - 3.3.10 available and 4.0.0.RC2 if possible

### ISSUE THREAD

**Issue by dsowza** [Litee/chocolatey-packages#6]
A newer version of Grails is available 3.3.10.

And if possible, please provide the 4.0.0.RC2 as Pre-Release in Chocolatey.
Thanks.

https://github.com/grails/grails-core/releases

**Comment by Litee** [comment]
3.3.10 - will update, thanks for reminding
4.0.0.RC2 - I don't want to publish release candidates, so will wait until stable version is published

**Comment by dsowza** [comment]
The new version 4.0.0 was released on July 11.

**Comment by dsowza** [comment]
Thank you!
